#!/usr/bin/env bash

echo_color() {
    color="${1}"
    shift 1
    echo -e "\e[0;${color}m${@}\e[0m"
}

info() {
    echo_color 34 "[>] ${@}"
    sleep 1
}

die() {
    echo_color 31 "[X] ${@}"
    exit 1
}

hostname="raspberry-pi"

if [[ ${#} -lt 1 ]]; then
    echo "Usage: $(basename ${0}) device [template-image]"
    exit 1
fi

dev="${1}"
template="${2}"

[[ ! -e "${dev}" ]] && die "Device does not exist: ${dev}"
[[ ! -z "${template}" && ! -e "${template}" ]] && \
    die "Template does not exist: ${template}"
(mount | grep "${dev}" &> /dev/null) && die "Device is mounted! Unmount first."

[[ -z "${template}" ]] && \
    info "Warning: No template image specified. Creating stock install."

info "Partitioning disk..."
cat <<EOM | fdisk "${dev}"
p
o
n
p
1

+100M
t
c
n
p
2


w
EOM

info "Creating file systems..."

mkfs.vfat "${dev}1"
mkfs.f2fs "${dev}2"

info "Mounting file systems..."
mkdir -v /var/tmp/boot
mkdir -v /var/tmp/root
mount -v "${dev}1" /var/tmp/boot
boot_ok=${?}
mount -v "${dev}2" /var/tmp/root
root_ok=${?}

if [[ "${boot_ok}" -ne 0 || "${root_ok}" -ne 0 ]]; then
    die "Failed to mount partitions!"
fi

info "Retrieving latest arch linux image..."
wget -N http://archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz -P /var/tmp

info "Creating root directory..."
tar xvf /var/tmp/ArchLinuxARM-rpi-2-latest.tar.gz -C /var/tmp/root
sync
info "Creating boot directory..."
mv -v /var/tmp/root/boot/* /var/tmp/boot

info "Re-mounting boot into the root file system..."
umount -v /var/tmp/boot
mount -v "${dev}1" /var/tmp/root/boot

if [[ ! -z "${template}" ]]; then
    info "Applying template image..."
    tar xvf "${template}" -C /var/tmp/root
fi

info "Setting hostname: ${hostname}"
echo "${hostname}" > /var/tmp/root/etc/hostname

info "Unmounting file systems..."
umount -v /var/tmp/root/boot
umount -v /var/tmp/root
