#!/usr/bin/env bash
################################################################################
# add-user - creates a new user account (including home directory on NFS) and
# pushes the changes out to the cluster.
################################################################################

if [[ -z "${PICLE_HOME}" ]]; then
    PICLE_HOME="$(cd "$(dirname "$0")" && pwd)/.."
fi
source "${PICLE_HOME}/shared/functions.sh" \
    || (echo "PICLE_HOME is not set!"; exit 1)
load_config

if [[ "${#}" -ne 1 ]]; then
    echo "Usage: $(basename ${0}) <username>"
    exit 1
fi
user_name="${1}"

echo "Creating new user: ${user_name}"

useradd -b ${USER_HOME_DIR} -m -G users "${user_name}"
if [[ ${?} -ne 0 ]]; then
    echo "Failed to create new user; exiting"
    exit 1
fi
${PICLE_HOME}/admin/update-passwd
