#!/usr/bin/env bash
################################################################################
# del-user - deletes an existing user account and pushes the changes out to the
# cluster. **NOTE:** the user's home directory will be erased. Make backups if
# necessary.
################################################################################

if [[ -z "${PICLE_HOME}" ]]; then
    PICLE_HOME="$(cd "$(dirname "$0")" && pwd)/.."
fi
source "${PICLE_HOME}/shared/functions.sh" \
    || (echo "PICLE_HOME is not set!"; exit 1)

if [[ "${#}" -ne 1 ]]; then
    echo "Usage: $(basename ${0}) <username>"
    exit 1
fi
user_name="${1}"

echo "Deleting user: ${user_name}"

userdel -r "${user_name}"
if [[ ${?} -ne 0 ]]; then
    echo "Failed to delete user; exiting"
    exit 1
fi

${PICLE_HOME}/admin/update-passwd
